### ISSUE TITLE
npm does not resolve RxJS dependency

### ISSUE THREAD

**Issue by jskulavik** [WebRxJS/WebRx#10]
Hi @oliverw, when installing WebRx with npm (v 2.7.4) WebRx installs, but RxJS does not.  This is an excellent project by the way, thank you for putting it out there!

**Comment by oliverw** [comment]
**Update**: Fixing this is not possible. They only way to get the requested behavior would be to declare *rx* as a NPM-PeerDepedency. But since peerDependency do not get installed automatically anymore this won't help either. 

Therefore the recommended approach is to declare *"rx": "^4.0.0"* as direct dependency of your project.
