### ISSUE TITLE
Conditional Command executed even when the condition is falsy

### ISSUE THREAD

**Issue by adicirstei** [WebRxJS/WebRx#20]
I'm not sure if I am doing something wrong or is a bug. If you press the button, the command is not getting executed when there's no url in the input field but executed if you hit enter.

Here's my code:

```html
<div>
  <input data-bind="textInput: @url, keyPress: {'enter': addBookmark}" />
  <button data-bind="command: addBookmark"> + </button>
  <ul data-bind="foreach: bookmarks">
    <li  data-bind="text: $data"></li>
  </ul>
</div>
```

```js
function viewModel() {
  this.url = wx.property('')
  this.bookmarks = wx.list()
  this.addBookmark = wx.command(function(){
    this.bookmarks.add(this.url())
    this.url("")
  }, wx.whenAny(this.url, function(url) {
            return url.match(/^https?:\/\/.+$/)
    }),
  this)
}

wx.applyBindings(new viewModel())

```

You can take a look at the pen linked bellow:
[http://codepen.io/adicirstei/pen/qOKzeW?editors=101](http://codepen.io/adicirstei/pen/qOKzeW?editors=101)

**Comment by oliverw** [comment]
No, you aren't doing anything wrong. What you are experiencing here is the result of two things:

1. WebRx's Command implementation was closely modeled around the .Net <code>ICommand</code> interface. Actually so close that I made the deliberate decision to allow invoking a command even though it currently can't execute. Thinking about it, that was a mistake because .Net's <code>ICommand</code> is an interface where it is not possible to prevent the invocation of<code>ICommand.execute()</code>. Contrary, in WebRx, commands are objects where adding logic for this is absolutely possible. And because of the latter, I agree with you that this is a bug.

2. Browsers always supported a feature called "implicit submission" where pressing the Enter-Key while focusing a form field would submit the enclosing form by simulating a click-event on the first Submit-Button of the form - regardless of that buttons enabled state. Somehow browsers tend to apply the same logic even at the absence of a form. That's why your command's <code>execute</code> handler is invoked.

**Workaround**

```javascript
this.addBookmark = wx.command(function(){
    if(!this.addBookmark.canExecute()) 
      return;
    
    this.bookmarks.add(this.url())
    this.url("")
  }, wx.whenAny(this.url, function(url) {
    return url.match(/^https?:\/\/.+$/)}),
  this);
```
